[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/pyodide/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "credentialless"

[[headers]]
  for = "*.js"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "*.wasm"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"